### ISSUE TITLE
Code not working with the demo code

### ISSUE THREAD

**Issue by danipolo** [bonartm/gscrape#3]
I'm trying to run the demo as you specify on the README and first it gives an error with Mongo:

```
Traceback (most recent call last):
  File "crawl.py", line 18, in <module>
    completions, serp = asyncio.get_event_loop().run_until_complete(scrape())
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "crawl.py", line 12, in scrape
    interface = SearchInterface(url, lat, lng, graphical, proxy)
TypeError: __init__() missing 1 required positional argument: 'mongo_uri'
```

Later on, if you addd the parameter, it gives you other error:

```
Traceback (most recent call last):
  File "crawl.py", line 19, in <module>
    completions, serp = asyncio.get_event_loop().run_until_complete(scrape())
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "crawl.py", line 14, in scrape
    await interface.launch()
AttributeError: 'SearchInterface' object has no attribute 'launch'
```

**Comment by bonartm** [comment]
I don't have the resources to work on this project any longer. I will archive it and leave a notification in the README. Feel free to fork and fix the code.
